### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by ethanaobrien** [EmulatorJS/emulatorjs.org#16]
@KingIzzymon @allancoding 

I wanted to get everyone's opinion before moving forward with this idea. So we all know ads aren't fun, it's one of the main reasons this project started in the first place, but servers, websites, domains, food, life isn't free. Therefore what if I put an ad on the demo page?

This wouldn't be for the whole site, just for the demo page, and should pay for any fees of utilities needed to host the website/project. It won't affect any developers using this project, only the demo page. It could also be used to show developers another feature.

Also @KingIzzymon I really liked the contributing page you added, what if we added a button there to watch an ad, fully voluntarily, to help contribute to the project. We could also offer developers the option to contribute by putting the ads on their sites, all on the contribution page.

I wanted to ask y'all about this before I did anything. What do y'all think?

**Comment by KingIzzymon** [comment]
It totally makes sense to me as long as it's not in the main project like you mentioned.

I'd just suggest that you include a banner on the demo page saying "This ad is only on the demo to help fund the project and will not be in the program itself"

Also add a similar note next to the "ads" input box on your `editor.js` code editor tool.

**Comment by ethanaobrien** [comment]
Awesome, I've created a google adsense account and have registered https://ads.emulatorjs.org/ although google says it may take up to 2 weeks to process

**Comment by allancoding** [comment]
Yes I think that is a great idea! The domain name can now pay for itself! 
And also if we have a public netplay server that will help the cost of the server.
For the iframe ad you can have text under the ad explaining why there is a ad and it's only for the demo page!

**Comment by illogic-al** [comment]
Well, as you mentioned, no one likes ads. This is your project, and you can do what you like, but before going the ads route, have you considered accepting donations. Like via Github Sponsors? Or maybe something like Patreon, or OpenCollective. 
You might be surprised at how other users are willing to support something they. use, if they can do so easily.
I mean, for e.g. if it's just hosting, I may be able to help w/ that depending on what's needed. ;-)

**Comment by ethanaobrien** [comment]
Yeah, Donations isn't a bad idea. I can probably start with donations and if needed add that single ad on the demo page, that would be there until you start the game.

The things I'm currently playing for for this project are heroku, google domains, and cloudfare. A total of $26 a month so not too much. I've thought about upgrading netlify, although that's $15 a month *per contributor* which is really dumb.

At the moment the only hosting prices I'm paying are for heroku, which is only $5 a month (not bad) and isn't even currently used for the main app (I use it to test some netplay stuff)

**Comment by illogic-al** [comment]
> Yeah, Donations isn't a bad idea. I can probably start with donations and if needed add that single ad on the demo page, that would be there until you start the game.
> 
Yep. And, with Sponsorships in particular you can see how much interest there is in the project being supported by others. If there's a lot more interest than you anticipate (based on Sponsorships) you may even be able to turn that into a full/semi full time gig. 

> The things I'm currently paying for for this project are heroku, google domains, and cloudflare. A total of $26 a month so not too much. I've thought about upgrading netlify, although that's $15 a month _per contributor_ which is really dumb.
> 
Have you heard of render? Comparable to heroku when they were good (in my opinion, they aren't anymore). But also, if the site is simple enough a hosted VPS might be all you need. I run quite a bit of infra all on a $10 linode. Email server, git server, static sites, nodejs blogs, and PHP database apps. All on 2 gigs of RAM (not a great idea but it can scale up easily if need be).

> At the moment the only hosting prices I'm paying are for heroku, which is only $5 a month (not bad) and isn't even currently used for the main app (I use it to test some netplay stuff)
> 
> Cloudflare is to be able to have site optimizations and protection

**Comment by ethanaobrien** [comment]
> Have you heard of render.com? Comparable to heroku when they were good (in my opinion, they aren't anymore). But also, if the site is simple enough a hosted VPS might be all you need. I run quite a bit of infra all on a $10 linode. Email server, git server, static sites, nodejs blogs, and PHP database apps. All on 2 gigs of RAM (not a great idea but it can scale up easily if need be). I previously had it on their $5/mo 1 gig RAM plan for years.

I haven't heard of them. Do so they support full server side processing and response like heroku? Also, is the pricing per server or per user? The current heroku plan I have is only $5 a month and has plenty of runtime hours available

> I suspect you could probably get at least a years worth of hosting via GitHub Sponsors. Can't hurt to try!

I set it up for the main project!

**Comment by illogic-al** [comment]
Render's free plan seems to be the same as heroku's intro $5 plan. But you can get t TLS certs + https/2 with this fee plan.

**Comment by ethanaobrien** [comment]
If I'm not mistaken, I'm pretty sure heroku does https for you (it's always been automatically on on my sites) either way that wouldn't matter since I've been proxying everything through cloudflare which uses it's own tls certificate.

How does it support https/2 for you? Wouldn't you need to program that in if it was a web application? I use netlify for hosting the main site (and it supports all that). I only use heroku for running the netplay server. Even if I moved my application over, I'm pretty sure that I'd still need to write http2 support into my application

**Comment by illogic-al** [comment]
HTTP/2 doesn't need any config application side. It works (or not), based on the TLS ciphers you are using. 
Based on those, the browsers (client) enable it or not. If you're using cloudflare then it's probably enabled.
Actually I just checked and https://emulatorjs.org is using HTTP/3, likely thanks to cloudflare's TLS choices.

**Comment by ethanaobrien** [comment]
Then from the sounds of it it should all be good
