### ISSUE TITLE
fast forward button in demo UI

### ISSUE THREAD

**Issue by bbeco** [EmulatorJS/emulatorjs.org#17]
EmulatorJS is amazing!
Thank you very much for putting together this awesome project!

I think the RetroArch engine support a fast forward feature. Would it be possible to add a button in the demo UI to toggle it on and off?

Thanks in advance!

Andrea

**Comment by ethanaobrien** [comment]
I can look into this, I'm pretty sure I've looked at this before and I found that it would impact the performance, and we're running in a web browser so we need as much performance as possible. If it doesn't impact it too badly I'll add this
